[package]
name = "coinarbitrage"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
ureq = { version = "2.5.0", features = ["json"] }
anyhow = "1.0.66"
serde-aux = "4.1.2"
tabled = "0.10.0"
thousands = "0.2.0"
